/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/new_account_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  Session: () => import('#controllers/session_controller'),
  Workspace: () => import('#controllers/workspace_controller'),
  Settings: () => import('#controllers/settings_controller'),
}
