/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'onboardingCompleted', 'password', 'preferredTheme', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare onboardingCompleted: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare preferredTheme: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkspaceMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'userId', 'workspaceId'] as const
  $columns = WorkspaceMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare userId: number
  @column()
  declare workspaceId: number
}

export class WorkspaceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'ownerUserId', 'slug', 'updatedAt'] as const
  $columns = WorkspaceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare ownerUserId: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
